---
- hosts: node
  tasks: 
  - name: creating a webserver and copying a file 
    package: 
      name: apache2
      state: present
  - name: service start apache2
    service:
      name: apache2
      state: stopped
  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
